services:
  web:
    image: python:3.9-slim
    container_name: simulation_webapp
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python app.py"
    ports:
      - "12345:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=superstrongpassword
      - DATABASE_NAME=simulation_db

  db:
    image: mariadb:10.6
    container_name: simulation_db
    environment:
      MYSQL_ROOT_PASSWORD: superstrongpassword
      MYSQL_DATABASE: simulation_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: simulation_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: superstrongpassword
    ports:
      - "12346:80"
    depends_on:
      - db

volumes:
  db_data:
